version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Redis in-memory datastore
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  # Redis Commander - Web UI for Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    env_file:
      - .env
    ports:
      - "8081:8081"

  app:
    image: sanad:latest
    container_name: app
    hostname: app
    ports:
      - "8080:8080"
      - "8039:8039"
    env_file: .env
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - postgres
      - redis


## Named volumes for data persistence
#volumes:
#  postgres_data:
#  redis_data: